services:
  scraper:
    build: ./scrapper
    container_name: waze_scraper
    volumes:
      - ./scrapper:/app
    command: bash -c "python scrapper.py && tail -f /dev/null"

  mongo:
    image: mongo:latest
    container_name: waze_mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dumbuser
      - MONGO_INITDB_ROOT_PASSWORD=dumbpassword

  redis_poisson_lru:
    image: redis:latest
    container_name: redis_poisson_lru
    command: redis-server --maxmemory 10mb --maxmemory-policy allkeys-lru

  redis_poisson_lfu:
    image: redis:latest
    container_name: redis_poisson_lfu
    command: redis-server --maxmemory 20mb --maxmemory-policy allkeys-lfu

  redis_pareto_lru:
    image: redis:latest
    container_name: redis_pareto_lru
    command: redis-server --maxmemory 20mb --maxmemory-policy allkeys-lru

  redis_pareto_lfu:
    image: redis:latest
    container_name: redis_pareto_lfu
    command: redis-server --maxmemory 20mb --maxmemory-policy allkeys-lfu

  traffic_generator_poisson_lru:
    build: ./traffic_generator
    container_name: traffic_generator_poisson_lru
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://dumbuser:dumbpassword@mongo:27017
      - REDIS_URI=redis://redis_poisson_lru:6379
      - DISTRIBUTION=poisson
      - EVICTION_POLICY=allkeys-lru
    volumes:
      - ./traffic_generator:/app
    command: python traffic_generator.py

  traffic_generator_poisson_lfu:
    build: ./traffic_generator
    container_name: traffic_generator_poisson_lfu
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://dumbuser:dumbpassword@mongo:27017
      - REDIS_URI=redis://redis_poisson_lfu:6379
      - DISTRIBUTION=poisson
      - EVICTION_POLICY=allkeys-lfu
    volumes:
      - ./traffic_generator:/app
    command: python traffic_generator.py

  traffic_generator_pareto_lru:
    build: ./traffic_generator
    container_name: traffic_generator_pareto_lru
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://dumbuser:dumbpassword@mongo:27017
      - REDIS_URI=redis://redis_pareto_lru:6379
      - DISTRIBUTION=pareto
      - EVICTION_POLICY=allkeys-lru
    volumes:
      - ./traffic_generator:/app
    command: python traffic_generator.py

  traffic_generator_pareto_lfu:
    build: ./traffic_generator
    container_name: traffic_generator_pareto_lfu
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://dumbuser:dumbpassword@mongo:27017
      - REDIS_URI=redis://redis_pareto_lfu:6379
      - DISTRIBUTION=pareto
      - EVICTION_POLICY=allkeys-lfu
    volumes:
      - ./traffic_generator:/app
    command: python traffic_generator.py

volumes:
  mongo_data:
  traffic_generator_data:
