services:
  scraper:
    build: ./scrapper
    container_name: waze_scraper
    volumes:
      - ./scrapper:/app
    command: bash -c "python scrapper.py && tail -f /dev/null"

  mongo:
    image: mongo:latest
    container_name: waze_mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dumbuser
      - MONGO_INITDB_ROOT_PASSWORD=dumbpassword

  data_filtering:
    build: ./data_filtering
    environment:
      - MONGO_USER=dumbuser
      - MONGO_PASS=dumbpassword
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=admin
      - MONGO_COLLECTION=alerts
      - OUTPUT_FILE=/data/clean/incidents_clean.csv
    depends_on:
      - mongo
    volumes:
      - ./data:/data
      - ./data_filtering:/app

  data_processing:
    build: ./data_processing
    volumes:
      - ./data:/data
      - ./data_processor:/app

volumes:
  mongo_data:
